---
- name: Update hosts file (Linux)
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.ip | regex_escape() }}\\s+{{ item.domain | regex_escape() }}$"
    line: "{{ item.ip }} {{ item.domain }}"
    state: present
  loop: "{{ relay_infrastructure }}"
  when: ansible_os_family != "Windows"

- name: Update hosts file (Windows)
  ansible.windows.win_hosts:
    state: present
    canonical_name: "{{ item.domain }}"
    ip_address: "{{ item.ip }}"
  loop: "{{ relay_infrastructure }}"
  when: ansible_os_family == "Windows"