---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure nginx is enabled and running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Create SSL directory
  ansible.builtin.file:
    path: /etc/nginx/ssl/
    state: directory
    mode: '0755'

- name: Copy relay certificate and key
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/ssl/{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "linux-selfsigned.crt", dest: "relay.crt", mode: "0644" }
    - { src: "linux-selfsigned.key", dest: "relay.key", mode: "0600" }

- name: Template nginx config
  ansible.builtin.template:
    src: relay_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx