---
- name: Apply Network Configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common_net

- name: Deploy Snake Eyes Backend
  hosts: backend
  gather_facts: true
  become: true
  roles:
    - snake_server

- name: Deploy C2 Relay Servers
  hosts: relays
  gather_facts: true
  become: true
  roles:
    - snake_relay

- name: Deploy Linux Agent Service
  hosts: linux_agents
  gather_facts: true
  become: true
  roles:
    - snake_agent_linux

- name: Deploy Windows Agent Service
  hosts: windows_agents:windows_dns_agents
  gather_facts: true
  roles:
    - snake_agent_windows