---
- name: Verify Linux Relays and Backend
  hosts: backend, relays
  gather_facts: no
  become: no  # <--- This overrides the ansible.cfg globally for this play
  tasks:
    - name: Ping Linux hosts
      ping:

- name: Verify Windows Agents
  hosts: agents
  gather_facts: no
  become: no  # <--- This prevents the "sudo" error on Windows
  tasks:
    - name: Ping Windows hosts
      win_ping: