---
- name: Test Linux Relays
  hosts: relays
  gather_facts: no
  tasks:
    - name: Ping Linux
      ping:

- name: Test Blue Team Windows Agents
  hosts: agents
  gather_facts: no
  tasks:
    - name: Ping Windows
      win_ping: