backend_internal_ip: "100.65.4.169"

relay_infrastructure:
  - { ip: "100.65.7.21", domain: "midevil-scoring-engine.com" }
  - { ip: "100.65.3.146", domain: "midevil-dashboard.local" }
  - { ip: "100.65.3.142", domain: "midevil.domain.local" }
  - { ip: "100.65.7.4", domain: "scoring-midevil.com" }
  - { ip: "100.65.3.78", domain: "scorify.com" }
  - { ip: "100.65.2.64", domain: "score-agent.local" }
  - { ip: "100.65.2.57", domain: "score-engine.local" }
  - { ip: "100.65.6.66", domain: "debian-mirror-useast.com" }
  - { ip: "100.65.4.36", domain: "microsoft-azure-useast.com" }
  - { ip: "100.65.7.147", domain: "score-check-agent.local" }

agent_dest_win: "C:\\ProgramData\\Microsoft\\Network\\Settings\\"

agent_dest_lin: "/etc/qemu/"

# Linux Credentials (Relays and Linux Agents)
ansible_user: "crimsonteam"
ansible_password: "crims0nwinz!"

# Windows Credentials (Windows Agents)
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: ntlm
ansible_winrm_user: "crimsonteam"
ansible_winrm_password: "crims0nwinz!"